### PR TITLE
Added isDisplay function and IsDisplay public function, + support for specifying display ID when adding regions

### PR DESCRIPTION
**Pull request by samverstocken**
Have not done the equivalent changes in js9.min.js. Is there some sort of automatic script for that?

### CODE REVIEW

**Comment by ericmandel** [comment]
Three comments before we get into this:

1. if you have run configure, you should be able to do:
````
    make js9min
````
to generate the min file and the two allinone files (4 files to push when changing js9.js).

2. I think your PR is almost the same as im.lookupDisplay(), except that my routine always returns a valid display. It might be simpler if we add an optional mustExist arg to lookupDisplay to return null if there is no display of the specified name:
````
  im.lookupDisplay("foo")          # (current behavior) returns first valid display if "foo" is not a display
  im.lookupDisplay("foo", true)    # returns false if "foo" is not a display
````
And then we just make a public routine to correspond. Or do you have something else in mind?

3. Are you having trouble specifying a display id when creating regions? This works for me:
````
JS9.AddRegions("circle", {display: "myJS9"})
````
If you have a case where it does not work, please let me know!

**Comment by samverstocken** [comment]
A typical command I would have for adding regions would be:

JS9.AddRegions('ellipse(280.4497,280.6714,126.4498,73.1900,66.3000)', {rotatable:false,resizable:true,color:'white',movable:false,zoomable:true,removable:false,changeable:true,lockMovementX:false,lockMovementY:false,lockRotation:false}, {display:'GALEXNUV'});

**Comment by ericmandel** [comment]
@samverstocken The changes to Image.prototype.lookupDisplay look correct, thanks. The changes to LookupDisplay are not quite correct: you don't take care of the case where a string id is passed as the first arg. These two should be equivalent:
````
JS9.LookupDisplay("foo")
JS9.LookupDisplay({display: "foo"})
````
In fact, the first call is the only "natural" way to pass the new mustExist switch:
````
JS9.LookupDisplay("foo", false)
JS9.LookupDisplay(null, false, {display: "foo"})
````
So I think you just need to change:
````
var obj = JS9.parsePublicArgs(arguments);
return JS9.lookupDisplay(obj.display, obj.argv[1]);
````
to something like this:
````
var obj = JS9.parsePublicArgs(arguments);
var display = obj.argv[0] || obj.display.id;
return JS9.lookupDisplay(display, obj.argv[1]);
````
But I haven't tested this, just looking at the code.

I don't understand the need for the proposed change to AddRegions. Can we please back out of that and just deal with lookupDisplay in the PR? Then you can explain the need in a separate PR. It looks to me like it should work as currently coded, so I need to know what the problem is.

**Comment by samverstocken** [comment]
@ericmandel You are absolutely right regarding the addRegions, that was not needed after all. The reason I brought the change back was because I was mistaken when I rolled back the first time: I didn't change the display argument back to obj.display as it was originally. 
I actually don't have any experience with JavaScript, I am just trying to make it work for my case and in the meantime helping where I can.

**Comment by ericmandel** [comment]
@samverstocken We're getting close and it would be good for you to have the credit for this mod. Here's are the small changes we need:

1. Image.prototype.lookupDisplay: Very reluctantly, we'll have to remove the ES6 syntax:
````
mustExist = true
```` 
in the calling sequence and replace it with the older syntax in the code:
````
if( mustExist === undefined ) mustExist = true;
````
The problem is that we support a lot of pre-university schools, many of whom might not have upgraded their browser since ES6 was ratified a year ago. Next year I hope to convert to ES6.

2. LookupDisplay: did you testing show that "mustExist = true" is necessary here? I would have thought that passing obj.argv[1] to the underlying call would be enough. That is, we should be able to use:
````
JS9.mkPublic("LookupDisplay", "lookupDisplay");
````
Or did you find a problem with this?

3. Before you re-make everything, please git pull the current js9. A few days ago, I changed the allinone build so that there is no longer a date in the allinone files. This will prevent the conflict that has happened with the current files.

**Comment by samverstocken** [comment]
@ericmandel I will apply the syntax as you describe it. As for the necessity of "mustExist = true", it isn't a matter of tests, it is me still in the process of understanding the JavaScript language and to a certain extent mimicking similar functions in js9.js untill it works. But I will replace with 'JS9.mkPublic("LookupDisplay", "lookupDisplay");' and test. I will also pull the latest commits.

**Comment by ericmandel** [comment]
@samverstocken this looks correct. I'll merge it and make final minor mods (including documentation). Thanks for contributing!

**Comment by ericmandel** [comment]
@samverstocken OK, I found a problem with the code as we implemented it. I have fixed it all up and updated into GitHub.

**Pull request merged**
