### PR TITLE
Add api links to the HTML documentation

### PR DESCRIPTION
**Pull request by DougBurke**
Provide ids for the commands so that they can be linked to, and do so within the API.

### CODE REVIEW

**Comment by DougBurke** [comment]
This is an experiment to see if it looks good. I changed to HTML5 from HTML 4.01 transitional for the API page. If I had time I'd use styles to make the page a bit-more consistent and easier to maintain, rather than copy/paste (I may do this in a future PR).

**Comment by ericmandel** [comment]
@DougBurke Very grateful for your work. Regarding HTML5, did you run the result through the W3C validation service at https://validator.w3.org? If not, would you please do so? I'm trying to ensure the JS9 web pages validate properly (except for occasional use of the HTM5 data-xxx construct) and I've not had much luck with upgrading to HTML5.

**Comment by DougBurke** [comment]
Sorry. I didn't have time last night. The complaints are mainly about using HTML4 era conventions (e.g. font tags rather than CSS). I'll see what I can cook up.

**Comment by ericmandel** [comment]
This will be great. Let me know when you are more or less finished and I'll review it.

**Comment by DougBurke** [comment]
@ericmandel - this now validates. I think there are more changes that could be done - e.g. instead of using h3/h4/h5 use h1/h2/h3; additional styling of the elements; more "clean up" of the HTML - but I don't think that's relevant to this PR (and I don't have time for it just now). So it's ready for review.

**Comment by DougBurke** [comment]
ps I like to commit lots of small changes as it's easier to see what I've changed, but I can squash them into a single change once they've reviewed if that would be preferable.

**Comment by ericmandel** [comment]
Thanks for doing this, I'll review it  a bit later in the morning. I prefer to see the history of changes as they are made, so let's not squash it.

**Pull request merged**
